/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated user context */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated user context */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks */
        get: {
            parameters: {
                query?: {
                    type?: number;
                    status?: string;
                    assignee?: number;
                    priority?: number;
                    client_id?: string;
                    due_from?: string;
                    due_to?: string;
                    has_photos?: boolean;
                    mine?: boolean;
                    sort?: "created_at" | "due_at" | "priority" | "board_position";
                    dir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Task"][];
                            meta?: {
                                page?: number;
                                per_page?: number;
                                total?: number;
                                last_page?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            responses: {
                /** @description Task created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update task */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{task}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update task status */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Invalid transition */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clients */
        get: {
            parameters: {
                query?: {
                    search?: string;
                    sort?: "name" | "created_at";
                    dir?: "asc" | "desc";
                    page?: number;
                    per_page?: number;
                    archived?: "all" | "only";
                    trashed?: "with" | "only";
                    tenant_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of clients */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Client"][];
                            meta?: components["schemas"]["ListMeta"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: email */
                        email?: string | null;
                        phone?: string | null;
                        notes?: string | null;
                        /** @description Send a welcome email to the client (requires email) */
                        notify_client?: boolean;
                        tenant_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description Created client */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/bulk-archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive multiple clients */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Clients archived */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Client"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete multiple clients */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Clients deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example deleted */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View client */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    client: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Client details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete client */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    client: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update client */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    client: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: email */
                        email?: string | null;
                        phone?: string | null;
                        notes?: string | null;
                        tenant_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description Updated client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/clients/{client}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    client: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        /** Unarchive client */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    client: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unarchived client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore client */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    client: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Restored client */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Watch task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watching task */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Unwatch task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Not watching */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task}/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create task subtask */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskSubtask"];
                };
            };
            responses: {
                /** @description Created subtask */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskSubtask"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task}/subtasks/{subtask}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete task subtask */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                    subtask: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update task subtask */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                    subtask: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskSubtask"];
                };
            };
            responses: {
                /** @description Updated subtask */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskSubtask"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{task}/subtasks/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder subtasks */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        order?: string[];
                    };
                };
            };
            responses: {
                /** @description Reordered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/tasks/{task}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List task comments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of comments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskComment"][];
                    };
                };
            };
        };
        put?: never;
        /** Create task comment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        body?: string;
                        mentions?: string[];
                        files?: string[];
                    };
                };
            };
            responses: {
                /** @description Created comment */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskComment"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles */
        get: {
            parameters: {
                query?: {
                    scope?: string;
                    tenant_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of roles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"][];
                    };
                };
            };
        };
        put?: never;
        /** Create role */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            responses: {
                /** @description Role */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete role */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update role */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
            responses: {
                /** @description Updated role */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/uploads/{uploadId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    uploadId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filename: string;
                        task_id: string;
                        field_key: string;
                        section_key: string;
                    };
                };
            };
            responses: {
                /** @description Uploaded file info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            file_id?: string;
                            name?: string;
                            variants?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{roleId}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign user to role */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
            responses: {
                /** @description Role assignment response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Role"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of teams */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"][];
                    };
                };
            };
        };
        put?: never;
        /** Create team */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            responses: {
                /** @description Team */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete team */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update team */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            responses: {
                /** @description Team */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/teams/{teamId}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync team employees */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        employee_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Team with employees */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List task types */
        get: {
            parameters: {
                query?: {
                    scope?: string;
                    tenant_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of types */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskType"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/{id}/copy-to-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy task type to tenant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        tenant_id?: string;
                    };
                };
            };
            responses: {
                /** @description Task type */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                content: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/bulk-copy-to-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy multiple task types to tenant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids?: string[];
                        tenant_id?: string;
                    };
                };
            };
            responses: {
                /** @description Task types */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskType"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete multiple task types */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids?: string[];
                    };
                };
            };
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export task type */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task type */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskType"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import task type */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskType"];
                };
            };
            responses: {
                /** @description Task type */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskType"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate task type schema and data */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        schema_json: Record<string, never>;
                        form_data?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
                /** @description Validation errors */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate task type schema and data */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        schema_json?: Record<string, never>;
                        form_data?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation errors */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/{task_type}/sla-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List SLA policies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Policies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TaskSlaPolicy"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create SLA policy */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskSlaPolicy"];
                };
            };
            responses: {
                /** @description Policy */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TaskSlaPolicy"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/{task_type}/sla-policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update SLA policy */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskSlaPolicy"];
                };
            };
            responses: {
                /** @description Policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TaskSlaPolicy"];
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete SLA policy */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/{task_type}/automations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List automations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Automations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TaskAutomation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create automation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskAutomation"];
                };
            };
            responses: {
                /** @description Automation */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TaskAutomation"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-types/{task_type}/automations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update automation */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskAutomation"];
                };
            };
            responses: {
                /** @description Automation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TaskAutomation"];
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete automation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_type: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List task statuses */
        get: {
            parameters: {
                query?: {
                    scope?: string;
                    tenant_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of task statuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TaskStatus"][];
                            meta?: {
                                page?: number;
                                per_page?: number;
                                total?: number;
                                last_page?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-statuses/{id}/copy-to-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy status to tenant */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        tenant_id?: string;
                    };
                };
            };
            responses: {
                /** @description Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskStatus"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifications */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Notification"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark notification read */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Marked read */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tasks grouped by status */
        get: {
            parameters: {
                query?: {
                    type_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Board columns */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                status?: components["schemas"]["TaskStatus"];
                                tasks?: components["schemas"]["Task"][];
                                meta?: {
                                    total?: number;
                                };
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-board/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move task on board */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        task_id: string;
                        status_slug: string;
                        index: number;
                    };
                };
            };
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Invalid move */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/reports/tasks/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task type overview metrics */
        get: {
            parameters: {
                query: {
                    type_id: string;
                    range?: "7" | "30" | "90";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics for task type */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            throughput?: {
                                /** Format: date */
                                x?: string;
                                y?: number;
                            }[];
                            cycle_time?: {
                                /** Format: date */
                                x?: string;
                                y?: number;
                            }[];
                            sla_attainment?: {
                                /** Format: date */
                                x?: string;
                                y?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Task: {
            id?: string;
            title?: string;
            status?: string;
            status_color?: string | null;
            /** Format: date-time */
            scheduled_at?: string;
            /** Format: date-time */
            due_at?: string | null;
            priority?: number | null;
            client_id?: string | null;
            assignee?: components["schemas"]["Employee"];
            counts?: {
                comments?: number;
                attachments?: number;
                watchers?: number;
                subtasks?: number;
            };
            /** @enum {string|null} */
            sla_chip?: "ok" | "dueSoon" | "breached" | null;
            is_watching?: boolean;
            client?: components["schemas"]["ClientSummary"] | null;
        };
        TaskComment: {
            id?: string;
            body?: string;
            user?: components["schemas"]["Employee"];
            mentions?: components["schemas"]["Employee"][];
            /** Format: date-time */
            created_at?: string;
        };
        TaskSlaPolicy: {
            id?: string;
            priority?: string;
            response_within_mins?: number | null;
            resolve_within_mins?: number | null;
            calendar_json?: Record<string, never> | null;
        };
        TaskAutomation: {
            id?: string;
            task_type_id?: string;
            event?: string;
            conditions_json?: Record<string, never> | null;
            actions_json?: Record<string, never>[];
            enabled?: boolean;
        };
        TaskSubtask: {
            id?: string;
            task_id?: string;
            title?: string;
            is_completed?: boolean;
            assigned_user_id?: string | null;
            is_required?: boolean;
            position?: number;
        };
        Role: {
            id?: string;
            name?: string;
            description?: string | null;
            level?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RoleAssignment: {
            user_id: string;
            tenant_id?: string | null;
        };
        Team: {
            id?: string;
            name?: string;
            description?: string | null;
            employees?: components["schemas"]["Employee"][];
        };
        TaskType: {
            id?: string;
            name?: string;
            /** @description Form schema. Text fields support string or {en,el} objects. */
            schema_json?: Record<string, never> | null;
            statuses?: {
                [key: string]: string[];
            } | null;
            status_flow_json?: Record<string, never> | null;
            tenant_id?: string | null;
            client_id?: string | null;
            abilities_json?: Record<string, never> | null;
            client?: components["schemas"]["ClientSummary"] | null;
        };
        TaskStatus: {
            id?: string;
            slug?: string;
            name?: string;
            color?: string;
            position?: number;
            tasks_count?: number;
            tenant_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Employee: {
            id?: string;
            name?: string;
            department?: string;
        };
        Notification: {
            id: string;
            message: string;
            link?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            read_at?: string | null;
        };
        ListMeta: {
            total?: number;
            per_page?: number;
            current_page?: number;
        };
        Error: {
            message: string;
        };
        AuthMeResponse: {
            /** @description Authenticated user with assigned roles and tenant context. */
            user?: Record<string, never>;
            abilities?: string[];
            client_abilities?: string[];
            features?: string[];
            permitted_client_ids?: string[] | null;
        };
        Client: {
            id?: string;
            tenant_id?: string;
            name?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            notes?: string | null;
            /** Format: date-time */
            archived_at?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        ClientSummary: {
            id?: string;
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
