openapi: 3.0.3
info:
  title: Asbuild API
  version: '1.0'
paths:
  /tasks:
    get:
      summary: List tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}:
    patch:
      summary: Update task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Updated task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{id}/status:
    post:
      summary: Update task status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Updated task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '422':
          description: Invalid transition
  /tasks/{id}/comments:
    get:
      summary: List task comments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskComment'
    post:
      summary: Create task comment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                mentions:
                  type: array
                  items:
                    type: integer
                files:
                  type: array
                  items:
                    type: integer
      responses:
        '201':
          description: Created comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskComment'
  /roles:
    get:
      summary: List roles
      parameters:
        - name: scope
          in: query
          schema:
            type: string
        - name: tenant_id
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
    post:
      summary: Create role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '200':
          description: Role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
  /roles/{id}:
    patch:
      summary: Update role
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '200':
          description: Updated role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
    delete:
      summary: Delete role
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
  /roles/{roleId}/assign:
    post:
      summary: Assign user to role
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleAssignment'
      responses:
        '200':
          description: Role assignment response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
  /teams:
    get:
      summary: List teams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    post:
      summary: Create team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
  /teams/{id}:
    patch:
      summary: Update team
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '200':
          description: Team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
    delete:
      summary: Delete team
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Deleted
  /teams/{teamId}/employees:
    post:
      summary: Sync team employees
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_ids:
                  type: array
                  items:
                    type: integer
      responses:
        '200':
          description: Team with employees
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
  /task-types:
    get:
      summary: List task types
      parameters:
        - name: scope
          in: query
          schema:
            type: string
        - name: tenant_id
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskType'
  /task-types/{id}/copy-to-tenant:
    post:
      summary: Copy task type to tenant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                tenant_id:
                  type: string
      responses:
        '200':
          description: Task type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskType'
  /task-statuses:
    get:
      summary: List task statuses
      parameters:
        - name: scope
          in: query
          schema:
            type: string
        - name: tenant_id
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of task statuses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskStatus'
  /task-statuses/{id}/copy-to-tenant:
    post:
      summary: Copy status to tenant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                tenant_id:
                  type: string
      responses:
        '200':
          description: Status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatus'
  /notifications:
    get:
      summary: List notifications
      responses:
        '200':
          description: List of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
  /notifications/{id}/read:
    post:
      summary: Mark notification read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Marked read
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        status:
          type: string
        scheduled_at:
          type: string
          format: date-time
        assignee:
          $ref: '#/components/schemas/Employee'
    TaskComment:
      type: object
      properties:
        id:
          type: integer
        body:
          type: string
        user:
          $ref: '#/components/schemas/Employee'
        mentions:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
        created_at:
          type: string
          format: date-time
    Role:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        level:
          type: integer
    RoleAssignment:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: integer
        tenant_id:
          type: string
          nullable: true
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        employees:
          type: array
          items:
            $ref: '#/components/schemas/Employee'
    TaskType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        schema_json:
          type: object
          nullable: true
        statuses:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          nullable: true
        tenant_id:
          type: integer
          nullable: true
    TaskStatus:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        scope:
          type: string
    Employee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Notification:
      type: object
      required:
        - id
        - message
        - created_at
      properties:
        id:
          type: integer
        message:
          type: string
        link:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        read_at:
          type: string
          format: date-time
          nullable: true
    ListMeta:
      type: object
      properties:
        total:
          type: integer
        per_page:
          type: integer
        current_page:
          type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
